Reworked update system Fixed French translation (again)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,19 +1,18 @@
 #!/bin/bash
+export QT_SELECT=5
 
 function errchk {
     "$@"
     local status=$?
     if [ $status -ne 0 ]; then
-        echo "Erreur avec $1" >&2
+        echo "Error with $1" >&2
         exit 1
     fi
     return $status
 }
 
-git submodule init
-git submodule update
+errchk git submodule init
+errchk git submodule update
 cd src
-errchk qmake
-echo "UNO est prêt pour la compilation"
-echo "Vous pouvez utiliser make"
-echo "Avant de lancer make, vérifiez que vous êtes bien dans le dossier UNO/src"
+errchk qmake 
+echo You can now run './buildUNO'
